const models = {
   users: {
      lid: null,
      afk: -1,
      afkReason: '',
      afkObj: {},
      banned: false,
      ban_temporary: 0,
      ban_times: 0,
      exp: 0,
      lastclaim: 0,
      lastrob: 0,
      premium: false,
      expired: 0,
      lastseen: 0,
      hit: 0,
      spam: 0,
      warning: 0,
      age: 0,
      reg_time: 0,
      registered: false,
   },
   groups: {
      activity: 0,
      mute: false,
      welcome: true,
      left: true,
      text_welcome: 'Hi @user👋\nWelcome to @subject\n\n@desc',
      text_left: 'Sayonara.... @user',
      autodetect: false,
      autosticker: false,
      antidelete: false,
      antilink: false,
      antivirtex: false,
      antisticker: false,
      antitagsw: false,
      antiporn: false,
      antiviewonce: false,
      antitoxic: false,
      member: {},
      expired: 0,
      stay: false
   },
   chats: {
      chat: 0,
      lastchat: 0,
      lastseen: 0
   },
   setting: {
      autobackup: false,
      anticall: true,
      self: false,
      online: true,
      antispam: true,
      debug: false,
      notifier: false,
      autodownload: false,
      groupmode: false,
      privatemode: false,
      noprefix: false,
      multiprefix: true,
      onlyprefix: '#',
      prefix: ['.', '/', '#', '!'],
      hidden: [],
      error: [],
      pluginDisable: [],
      lastReset: new Date * 1,
      sk_pack: 'moon - bot',
      sk_author: 'linktr.ee/moonxbot',
      toxic: ['jancok', 'bajingan', 'kontol', 'memek'],
      owners: ['6283866857978'],
      msg: '+greeting +tag👋\nTake a sad day and make it brighter. You\'re stronger than you think. Keep going.\n\n◦  *Database* : +db\n◦  *Source* : https://github.com/rifnd/moon-bot\n◦  *Rest API* : https://api.alyachan.dev\n\nIf there is a mistake or error, contact the owner.',
      style: 1,
      cover: 'https://i.ibb.co/GBsZR7j/image.jpg',
      link: 'https://chat.whatsapp.com/GfBgnkz1lAs7NUk7lnzCDk'
   }
}

module.exports = { models }